[package]
name = "rovkit"
version = "0.1.0"
edition = "2021"

[lib]
name = "rovkit"
path = "src/lib.rs"


#[features]
#default = ["sync"]
#sync = []
#async = ["reqwest/async", "tokio"]

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"], optional = true }
tokio = { version = "1", features = ["full"], optional = true }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

#[dependencies.reqwest]
#optional = true

#[dependencies.tokio]
#optional = true